verison: '3.3'
services:
  api:
    container_name: api_huggy_tst
    build: ./api
    restart: always
    env_file:
      - ./api/.env
    
  nginx:
    container_name: nginx_api
    build: ./nginx
    ports:
      - 8080:80

