services:
  api:
    container_name: api_huggy_tst
    build: ./api
    restart: always
    env_file:
      - ./api/.env
    environment:
      - SECRET_KEY=${SECRET_KEY}
    
  nginx:
    container_name: nginx_api
    build: ./nginx
    ports:
      - 8009:80

