version: '3.3'
services:
  api:
    container_name: api_huggy_unimed
    build: ./api
    restart: always
    env_file:
      - ./api/.env
    environment:
      - SECRET_KEY=${SECRET_KEY}
    
  nginx:
    container_name: nginx_api_huggy
    build: ./nginx
    ports:
      - 8009:8009
    depends_on:
      - api

